const models = {
   users: Object.freeze({
      afk: -1,
      afkReason: '',
      afkObj: {},
      age: 0,
      banned: false,
      ban_temporary: 0,
      ban_times: 0,
      premium: false,
      expired: 0,
      hit: 0,
      lastseen: 0,
      nama: '',
      register: false,
      regTime: 0,
      saldo: 0,
      token: '',
      warning: 0,
      example: [],
      allowedCommands: [],
      responseCount: 0 
   }),
   groups: Object.freeze({
      activity: 0,
      antidelete: false,
      antilink: false,
      antivirtex: true,
      antitagsw: false,
      filter: false,
      left: false,
      localonly: false,
      mute: false,
      viewonce: false,
      autosticker: true,
      member: {},
      text_left: '',
      text_welcome: '',
      welcome: true,
      expired: 0,
      stay: false,
      responseCount: 0 
   }),
   chats: Object.freeze({
      chat: 0,
      lastchat: 0,
      lastseen: 0,
      responseCount: 0 
   }),
   setting: Object.freeze({
      autodownload: true,
      autobio: false,
      antispam: true,
      debug: false,
      error: [],
      hidden: [],
      pluginDisable: [],
      receiver: [],
      groupmode: false,
      sk_pack: 'Sticker by',
      sk_author: '© Aiyam',
      self: false,
      noprefix: false,
      multiprefix: true,
      prefix: ['.', '#', '!', '/'],
      toxic: ["ajg", "ajig", "anjas", "anjg", "anjim", "anjing", "anjrot", "anying", "asw", "autis", "babi", "bacod", "bacot", "bagong", "bajingan", "bangsad", "bangsat", "bastard", "bego", "bgsd", "biadab", "biadap", "bitch", "bngst", "bodoh", "bokep", "cocote", "coli", "colmek", "comli", "dajjal", "dancok", "dongo", "fuck", "gelay", "goblog", "goblok", "guoblog", "guoblok", "hairul", "henceut", "idiot", "itil", "jamet", "jancok", "jembut", "jingan", "kafir", "kanjut", "kanyut", "keparat", "kntl", "kontol", "lana", "loli", "lont", "lonte", "mancing", "meki", "memek", "ngentod", "ngentot", "ngewe", "ngocok", "ngtd", "njeng", "njing", "njinx", "oppai", "pantek", "pantek", "peler", "pepek", "pilat", "pler", "pornhub", "pucek", "puki", "pukimak", "redhub", "sange", "setan", "silit", "telaso", "tempek", "tete", "titit", "toket", "tolol", "tomlol", "tytyd", "wildan", "xnxx"],
      online: true,
      onlyprefix: '+',
      owners: ['994408364923'],
      lastReset: new Date * 1,
      msg: "Selamat datang, +tag! 🌊 Kenalan yuk sama aku, bot pintar yang siap memudahkan hidupmu di WhatsApp! Aku bisa bantu cari informasi, melakukan tugas tertentu, dan semua itu langsung di sini! 🪸\n⚙️ Spesifikasi:\n◦ Modul: +module\n◦ Database: +db\n◦ Pustaka: Baileys v+version\n◦ Source: https://github.com/neoxr/neoxr-bot\n◦ Note 'Script ini telah diubh sedemikian rupa'\n✉️ Laporkan bug atau tanya tentang premium ke owner ya!",
      style: 4,
      cover: 'https://qu.ax/ygyeV.jpeg',
      link: 'https://whatsapp.com/channel/0029Vb61zzQ8KMqoLNcNLr3I'
   }),
   statistic: Object.freeze({
      totalResponses: 0,
      todayResponses: 0,
      lastReset: 0,
      dailyHistory: [] // Untuk menyimpan history per hari
   })
}

module.exports = { models }